# Generated by Django 3.1.7 on 2021-02-21 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='MacroCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MesoCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('macro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacked.macrocycle')),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutWeeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_nr', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('number', models.IntegerField()),
                ('meso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacked.mesocycle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacked.workoutdays')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacked.exercises')),
            ],
        ),
        migrations.AddField(
            model_name='workoutdays',
            name='week_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacked.workoutweeks'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='muscle_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jacked.musclegroups'),
        ),
    ]
